In [1]:
import os
import numpy as np
import skimage

In [2]:
input_dir='D:/clf-data'
category=['empty','not_empty']

In [3]:
data,labels=[],[]

In [4]:
from skimage.io import imread
from skimage.transform import resize
for ind,category in enumerate(category):
    for file in os.listdir(os.path.join(input_dir,category)):
        img_path=os.path.join(input_dir,category,file)
        img=imread(img_path)
        img=resize(img,(15,15))
        data.append(img.flatten())
        labels.append(ind)
data=np.array(data)
labels=np.array(labels)

In [5]:
data

array([[0.42900875, 0.43685188, 0.39371463, ..., 0.50419255, 0.50054123,
        0.48018387],
       [0.46212812, 0.46212812, 0.43075557, ..., 0.18932792, 0.19417843,
        0.1662428 ],
       [0.32647287, 0.31470816, 0.27957641, ..., 0.38530893, 0.38530893,
        0.35393638],
       ...,
       [0.33501445, 0.33528246, 0.30231314, ..., 0.24222187, 0.2841873 ,
        0.27697022],
       [0.3035818 , 0.33893682, 0.3352002 , ..., 0.30326822, 0.30891722,
        0.30623886],
       [0.34430422, 0.34744568, 0.31159131, ..., 0.30567501, 0.31172336,
        0.31018725]])

In [6]:
labels

array([0, 0, 0, ..., 1, 1, 1])

In [11]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(data,labels,test_size=0.25,random_state=42,shuffle=True,stratify=labels)

In [13]:
from sklearn.svm import SVC
classifier=SVC()
classifier.fit(xtrain,ytrain)

SVC()

In [14]:
parameters=[{'gamma':[0.01,0.25,0.75,0.9],'C':[1,10,100,1000],'kernel':['linear','sigmoid','rbf']}]
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV
grid=GridSearchCV(classifier,parameters)
grid.fit(xtrain,ytrain)

GridSearchCV(estimator=SVC(),
             param_grid=[{'C': [1, 10, 100, 1000],
                          'gamma': [0.01, 0.25, 0.75, 0.9],
                          'kernel': ['linear', 'sigmoid', 'rbf']}])

In [15]:
from sklearn.metrics import accuracy_score
best=grid.best_estimator_
ypred=best.predict(xtest)
accuracy_score(ytest,ypred)

1.0

In [16]:
from sklearn.model_selection import cross_val_score
cross_val_score(classifier,data,labels,cv=5)

array([0.99671593, 1.        , 1.        , 1.        , 1.        ])